(ns clobal.data.countries)

;; Autogenerated
(def
 countries
 {:TL
  {:currency :USD,
   :alpha_2_code :TL,
   :alpha_3_code :TLS,
   :name "Timor-Leste"},
  :GD
  {:currency :XCD,
   :alpha_2_code :GD,
   :alpha_3_code :GRD,
   :name "Grenada"},
  :SA
  {:currency :SAR,
   :alpha_2_code :SA,
   :alpha_3_code :SAU,
   :name "Saudi Arabia"},
  :LU
  {:currency :EUR,
   :alpha_2_code :LU,
   :alpha_3_code :LUX,
   :name "Luxembourg"},
  :ID
  {:currency :IDR,
   :alpha_2_code :ID,
   :alpha_3_code :IDN,
   :name "Indonesia"},
  :PF
  {:currency :XPF,
   :alpha_2_code :PF,
   :alpha_3_code :PYF,
   :name "French Polynesia"},
  :TO
  {:currency :TOP,
   :alpha_2_code :TO,
   :alpha_3_code :TON,
   :name "Tonga"},
  :CM
  {:currency :XAF,
   :alpha_2_code :CM,
   :alpha_3_code :CMR,
   :name "Cameroon"},
  :YT
  {:currency :EUR,
   :alpha_2_code :YT,
   :alpha_3_code :MYT,
   :name "Mayotte"},
  :PT
  {:currency :EUR,
   :alpha_2_code :PT,
   :alpha_3_code :PRT,
   :name "Portugal"},
  :LK
  {:currency :LKR,
   :alpha_2_code :LK,
   :alpha_3_code :LKA,
   :name "Sri Lanka"},
  :IR
  {:currency :IRR,
   :alpha_2_code :IR,
   :alpha_3_code :IRN,
   :name "Iran, Islamic Republic of"},
  :KW
  {:currency :KWD,
   :alpha_2_code :KW,
   :alpha_3_code :KWT,
   :name "Kuwait"},
  :VU
  {:currency :VUV,
   :alpha_2_code :VU,
   :alpha_3_code :VUT,
   :name "Vanuatu"},
  :IL
  {:currency :ILS,
   :alpha_2_code :IL,
   :alpha_3_code :ISR,
   :name "Israel"},
  :CL
  {:currency :CLP,
   :alpha_2_code :CL,
   :alpha_3_code :CHL,
   :name "Chile"},
  :QA
  {:currency :QAR,
   :alpha_2_code :QA,
   :alpha_3_code :QAT,
   :name "Qatar"},
  :IO
  {:currency :USD,
   :alpha_2_code :IO,
   :alpha_3_code :IOT,
   :name "British Indian Ocean Territory"},
  :SC
  {:currency :SCR,
   :alpha_2_code :SC,
   :alpha_3_code :SYC,
   :name "Seychelles"},
  :BE
  {:currency :EUR,
   :alpha_2_code :BE,
   :alpha_3_code :BEL,
   :name "Belgium"},
  :AQ
  {:currency nil,
   :alpha_2_code :AQ,
   :alpha_3_code :ATA,
   :name "Antarctica"},
  :VA
  {:currency :EUR,
   :alpha_2_code :VA,
   :alpha_3_code :VAT,
   :name "Holy See (Vatican City State)"},
  :GT
  {:currency :GTQ,
   :alpha_2_code :GT,
   :alpha_3_code :GTM,
   :name "Guatemala"},
  :GP
  {:currency :EUR,
   :alpha_2_code :GP,
   :alpha_3_code :GLP,
   :name "Guadeloupe"},
  :MC
  {:currency :EUR,
   :alpha_2_code :MC,
   :alpha_3_code :MCO,
   :name "Monaco"},
  :SK
  {:currency :EUR,
   :alpha_2_code :SK,
   :alpha_3_code :SVK,
   :name "Slovakia"},
  :SH
  {:currency :SHP,
   :alpha_2_code :SH,
   :alpha_3_code :SHN,
   :name "Saint Helena, Ascension and Tristan da Cunha"},
  :IT
  {:currency :EUR,
   :alpha_2_code :IT,
   :alpha_3_code :ITA,
   :name "Italy"},
  :SG
  {:currency :SGD,
   :alpha_2_code :SG,
   :alpha_3_code :SGP,
   :name "Singapore"},
  :CY
  {:currency :EUR,
   :alpha_2_code :CY,
   :alpha_3_code :CYP,
   :name "Cyprus"},
  :BJ
  {:currency :XOF,
   :alpha_2_code :BJ,
   :alpha_3_code :BEN,
   :name "Benin"},
  :GB
  {:currency :GBP,
   :alpha_2_code :GB,
   :alpha_3_code :GBR,
   :name "United Kingdom"},
  :PS
  {:currency nil,
   :alpha_2_code :PS,
   :alpha_3_code :PSE,
   :name "Palestine, State of"},
  :HR
  {:currency :HRK,
   :alpha_2_code :HR,
   :alpha_3_code :HRV,
   :name "Croatia"},
  :DK
  {:currency :DKK,
   :alpha_2_code :DK,
   :alpha_3_code :DNK,
   :name "Denmark"},
  :LA
  {:currency :LAK,
   :alpha_2_code :LA,
   :alpha_3_code :LAO,
   :name "Lao People's Democratic Republic"},
  :AR
  {:currency :ARS,
   :alpha_2_code :AR,
   :alpha_3_code :ARG,
   :name "Argentina"},
  :SZ
  {:currency :SZL,
   :alpha_2_code :SZ,
   :alpha_3_code :SWZ,
   :name "Swaziland"},
  :EH
  {:currency :MAD,
   :alpha_2_code :EH,
   :alpha_3_code :ESH,
   :name "Western Sahara"},
  :PR
  {:currency :USD,
   :alpha_2_code :PR,
   :alpha_3_code :PRI,
   :name "Puerto Rico"},
  :CC
  {:currency :AUD,
   :alpha_2_code :CC,
   :alpha_3_code :CCK,
   :name "Cocos (Keeling) Islands"},
  :IQ
  {:currency :IQD,
   :alpha_2_code :IQ,
   :alpha_3_code :IRQ,
   :name "Iraq"},
  :SE
  {:currency :SEK,
   :alpha_2_code :SE,
   :alpha_3_code :SWE,
   :name "Sweden"},
  :BM
  {:currency :BMD,
   :alpha_2_code :BM,
   :alpha_3_code :BMU,
   :name "Bermuda"},
  :WS
  {:currency :WST,
   :alpha_2_code :WS,
   :alpha_3_code :WSM,
   :name "Samoa"},
  :UZ
  {:currency :UZS,
   :alpha_2_code :UZ,
   :alpha_3_code :UZB,
   :name "Uzbekistan"},
  :IN
  {:currency :INR,
   :alpha_2_code :IN,
   :alpha_3_code :IND,
   :name "India"},
  :DO
  {:currency :DOP,
   :alpha_2_code :DO,
   :alpha_3_code :DOM,
   :name "Dominican Republic"},
  :GF
  {:currency :EUR,
   :alpha_2_code :GF,
   :alpha_3_code :GUF,
   :name "French Guiana"},
  :LC
  {:currency :XCD,
   :alpha_2_code :LC,
   :alpha_3_code :LCA,
   :name "Saint Lucia"},
  :BQ
  {:currency :USD,
   :alpha_2_code :BQ,
   :alpha_3_code :BES,
   :name "Bonaire, Sint Eustatius and Saba"},
  :GL
  {:currency :DKK,
   :alpha_2_code :GL,
   :alpha_3_code :GRL,
   :name "Greenland"},
  :ST
  {:currency :STD,
   :alpha_2_code :ST,
   :alpha_3_code :STP,
   :name "Sao Tome and Principe"},
  :SX
  {:currency :ANG,
   :alpha_2_code :SX,
   :alpha_3_code :SXM,
   :name "Sint Maarten (Dutch part)"},
  :GG
  {:currency :GBP,
   :alpha_2_code :GG,
   :alpha_3_code :GGY,
   :name "Guernsey"},
  :BZ
  {:currency :BZD,
   :alpha_2_code :BZ,
   :alpha_3_code :BLZ,
   :name "Belize"},
  :TV
  {:currency :AUD,
   :alpha_2_code :TV,
   :alpha_3_code :TUV,
   :name "Tuvalu"},
  :AW
  {:currency :AWG,
   :alpha_2_code :AW,
   :alpha_3_code :ABW,
   :name "Aruba"},
  :LR
  {:currency :LRD,
   :alpha_2_code :LR,
   :alpha_3_code :LBR,
   :name "Liberia"},
  :KY
  {:currency :KYD,
   :alpha_2_code :KY,
   :alpha_3_code :CYM,
   :name "Cayman Islands"},
  :UG
  {:currency :UGX,
   :alpha_2_code :UG,
   :alpha_3_code :UGA,
   :name "Uganda"},
  :AF
  {:currency nil,
   :alpha_2_code :AF,
   :alpha_3_code :AFG,
   :name "Afghanistan"},
  :AE
  {:currency :AED,
   :alpha_2_code :AE,
   :alpha_3_code :ARE,
   :name "United Arab Emirates"},
  :JO
  {:currency :JOD,
   :alpha_2_code :JO,
   :alpha_3_code :JOR,
   :name "Jordan"},
  :NI
  {:currency :NIO,
   :alpha_2_code :NI,
   :alpha_3_code :NIC,
   :name "Nicaragua"},
  :SM
  {:currency :EUR,
   :alpha_2_code :SM,
   :alpha_3_code :SMR,
   :name "San Marino"},
  :FO
  {:currency :DKK,
   :alpha_2_code :FO,
   :alpha_3_code :FRO,
   :name "Faroe Islands"},
  :GQ
  {:currency :XAF,
   :alpha_2_code :GQ,
   :alpha_3_code :GNQ,
   :name "Equatorial Guinea"},
  :KP
  {:currency :KPW,
   :alpha_2_code :KP,
   :alpha_3_code :PRK,
   :name "Korea, Democratic People's Republic of"},
  :CO
  {:currency :COP,
   :alpha_2_code :CO,
   :alpha_3_code :COL,
   :name "Colombia"},
  :MG
  {:currency :MGA,
   :alpha_2_code :MG,
   :alpha_3_code :MDG,
   :name "Madagascar"},
  :TZ
  {:currency :TZS,
   :alpha_2_code :TZ,
   :alpha_3_code :TZA,
   :name "Tanzania, United Republic of"},
  :SV
  {:currency :USD,
   :alpha_2_code :SV,
   :alpha_3_code :SLV,
   :name "El Salvador"},
  :MF
  {:currency :EUR,
   :alpha_2_code :MF,
   :alpha_3_code :MAF,
   :name "Saint Martin (French part)"},
  :EC
  {:currency :USD,
   :alpha_2_code :EC,
   :alpha_3_code :ECU,
   :name "Ecuador"},
  :CX
  {:currency :AUD,
   :alpha_2_code :CX,
   :alpha_3_code :CXR,
   :name "Christmas Island"},
  :HM
  {:currency :AUD,
   :alpha_2_code :HM,
   :alpha_3_code :HMD,
   :name "Heard Island and McDonald Islands"},
  :KH
  {:currency :KHR,
   :alpha_2_code :KH,
   :alpha_3_code :KHM,
   :name "Cambodia"},
  :CV
  {:currency :CVE,
   :alpha_2_code :CV,
   :alpha_3_code :CPV,
   :name "Cape Verde"},
  :ZW
  {:currency :ZWL,
   :alpha_2_code :ZW,
   :alpha_3_code :ZWE,
   :name "Zimbabwe"},
  :GI
  {:currency :GIP,
   :alpha_2_code :GI,
   :alpha_3_code :GIB,
   :name "Gibraltar"},
  :MU
  {:currency :MUR,
   :alpha_2_code :MU,
   :alpha_3_code :MUS,
   :name "Mauritius"},
  :HN
  {:currency :HNL,
   :alpha_2_code :HN,
   :alpha_3_code :HND,
   :name "Honduras"},
  :AL
  {:currency :ALL,
   :alpha_2_code :AL,
   :alpha_3_code :ALB,
   :name "Albania"},
  :MV
  {:currency :MVR,
   :alpha_2_code :MV,
   :alpha_3_code :MDV,
   :name "Maldives"},
  :LY
  {:currency :LYD,
   :alpha_2_code :LY,
   :alpha_3_code :LBY,
   :name "Libya"},
  :BL
  {:currency :EUR,
   :alpha_2_code :BL,
   :alpha_3_code :BLM,
   :name "Saint Barthélemy"},
  :AI
  {:currency :XCD,
   :alpha_2_code :AI,
   :alpha_3_code :AIA,
   :name "Anguilla"},
  :OM
  {:currency :OMR,
   :alpha_2_code :OM,
   :alpha_3_code :OMN,
   :name "Oman"},
  :HT
  {:currency :USD,
   :alpha_2_code :HT,
   :alpha_3_code :HTI,
   :name "Haiti"},
  :PM
  {:currency :EUR,
   :alpha_2_code :PM,
   :alpha_3_code :SPM,
   :name "Saint Pierre and Miquelon"},
  :PE
  {:currency :PEN,
   :alpha_2_code :PE,
   :alpha_3_code :PER,
   :name "Peru"},
  :BN
  {:currency :BND,
   :alpha_2_code :BN,
   :alpha_3_code :BRN,
   :name "Brunei Darussalam"},
  :TF
  {:currency :EUR,
   :alpha_2_code :TF,
   :alpha_3_code :ATF,
   :name "French Southern Territories"},
  :CA
  {:currency :CAD,
   :alpha_2_code :CA,
   :alpha_3_code :CAN,
   :name "Canada"},
  :CU
  {:currency :CUP,
   :alpha_2_code :CU,
   :alpha_3_code :CUB,
   :name "Cuba"},
  :MA
  {:currency :MAD,
   :alpha_2_code :MA,
   :alpha_3_code :MAR,
   :name "Morocco"},
  :PY
  {:currency :PYG,
   :alpha_2_code :PY,
   :alpha_3_code :PRY,
   :name "Paraguay"},
  :IS
  {:currency :ISK,
   :alpha_2_code :IS,
   :alpha_3_code :ISL,
   :name "Iceland"},
  :KN
  {:currency :XCD,
   :alpha_2_code :KN,
   :alpha_3_code :KNA,
   :name "Saint Kitts and Nevis"},
  :PN
  {:currency :NZD,
   :alpha_2_code :PN,
   :alpha_3_code :PCN,
   :name "Pitcairn"},
  :LB
  {:currency :LBP,
   :alpha_2_code :LB,
   :alpha_3_code :LBN,
   :name "Lebanon"},
  :ME
  {:currency :EUR,
   :alpha_2_code :ME,
   :alpha_3_code :MNE,
   :name "Montenegro"},
  :DJ
  {:currency :DJF,
   :alpha_2_code :DJ,
   :alpha_3_code :DJI,
   :name "Djibouti"},
  :KE
  {:currency :KES,
   :alpha_2_code :KE,
   :alpha_3_code :KEN,
   :name "Kenya"},
  :LV
  {:currency :LVL,
   :alpha_2_code :LV,
   :alpha_3_code :LVA,
   :name "Latvia"},
  :SI
  {:currency :EUR,
   :alpha_2_code :SI,
   :alpha_3_code :SVN,
   :name "Slovenia"},
  :MD
  {:currency :MDL,
   :alpha_2_code :MD,
   :alpha_3_code :MDA,
   :common_name "Moldova",
   :name "Moldova, Republic of"},
  :AU
  {:currency :AUD,
   :alpha_2_code :AU,
   :alpha_3_code :AUS,
   :name "Australia"},
  :RO
  {:currency :RON,
   :alpha_2_code :RO,
   :alpha_3_code :ROU,
   :name "Romania"},
  :SO
  {:currency :SOS,
   :alpha_2_code :SO,
   :alpha_3_code :SOM,
   :name "Somalia"},
  :KI
  {:currency :AUD,
   :alpha_2_code :KI,
   :alpha_3_code :KIR,
   :name "Kiribati"},
  :BO
  {:currency :BOB,
   :alpha_2_code :BO,
   :alpha_3_code :BOL,
   :common_name "Bolivia",
   :name "Bolivia, Plurinational State of"},
  :AD
  {:currency :EUR,
   :alpha_2_code :AD,
   :alpha_3_code :AND,
   :name "Andorra"},
  :VE
  {:currency :VEF,
   :alpha_2_code :VE,
   :alpha_3_code :VEN,
   :common_name "Venezuela",
   :name "Venezuela, Bolivarian Republic of"},
  :MO
  {:currency :MOP,
   :alpha_2_code :MO,
   :alpha_3_code :MAC,
   :name "Macao"},
  :VN
  {:currency :VND,
   :alpha_2_code :VN,
   :alpha_3_code :VNM,
   :name "Viet Nam"},
  :CF
  {:currency :XAF,
   :alpha_2_code :CF,
   :alpha_3_code :CAF,
   :name "Central African Republic"},
  :MX
  {:currency :MXN,
   :alpha_2_code :MX,
   :alpha_3_code :MEX,
   :name "Mexico"},
  :CN
  {:currency :CNY,
   :alpha_2_code :CN,
   :alpha_3_code :CHN,
   :name "China"},
  :BA
  {:currency :BAM,
   :alpha_2_code :BA,
   :alpha_3_code :BIH,
   :name "Bosnia and Herzegovina"},
  :VG
  {:currency :USD,
   :alpha_2_code :VG,
   :alpha_3_code :VGB,
   :name "Virgin Islands, British"},
  :NR
  {:currency :AUD,
   :alpha_2_code :NR,
   :alpha_3_code :NRU,
   :name "Nauru"},
  :LS
  {:currency :ZAR,
   :alpha_2_code :LS,
   :alpha_3_code :LSO,
   :name "Lesotho"},
  :RS
  {:currency :RSD,
   :alpha_2_code :RS,
   :alpha_3_code :SRB,
   :name "Serbia"},
  :BI
  {:currency :BIF,
   :alpha_2_code :BI,
   :alpha_3_code :BDI,
   :name "Burundi"},
  :VC
  {:currency :XCD,
   :alpha_2_code :VC,
   :alpha_3_code :VCT,
   :name "Saint Vincent and the Grenadines"},
  :SR
  {:currency :SRD,
   :alpha_2_code :SR,
   :alpha_3_code :SUR,
   :name "Suriname"},
  :RU
  {:currency :RUB,
   :alpha_2_code :RU,
   :alpha_3_code :RUS,
   :name "Russian Federation"},
  :CK
  {:currency :NZD,
   :alpha_2_code :CK,
   :alpha_3_code :COK,
   :name "Cook Islands"},
  :MK
  {:currency :MKD,
   :alpha_2_code :MK,
   :alpha_3_code :MKD,
   :name "Macedonia, Republic of"},
  :CI
  {:currency :XOF,
   :alpha_2_code :CI,
   :alpha_3_code :CIV,
   :name "Côte d'Ivoire"},
  :WF
  {:currency :XPF,
   :alpha_2_code :WF,
   :alpha_3_code :WLF,
   :name "Wallis and Futuna"},
  :NL
  {:currency :EUR,
   :alpha_2_code :NL,
   :alpha_3_code :NLD,
   :name "Netherlands"},
  :BB
  {:currency :BBD,
   :alpha_2_code :BB,
   :alpha_3_code :BRB,
   :name "Barbados"},
  :FJ
  {:currency :FJD,
   :alpha_2_code :FJ,
   :alpha_3_code :FJI,
   :name "Fiji"},
  :TH
  {:currency :THB,
   :alpha_2_code :TH,
   :alpha_3_code :THA,
   :name "Thailand"},
  :US
  {:currency :USD,
   :alpha_2_code :US,
   :alpha_3_code :USA,
   :name "United States"},
  :GU
  {:currency :USD,
   :alpha_2_code :GU,
   :alpha_3_code :GUM,
   :name "Guam"},
  :ZM
  {:currency :ZMW,
   :alpha_2_code :ZM,
   :alpha_3_code :ZMB,
   :name "Zambia"},
  :SN
  {:currency :XOF,
   :alpha_2_code :SN,
   :alpha_3_code :SEN,
   :name "Senegal"},
  :JP
  {:currency :JPY,
   :alpha_2_code :JP,
   :alpha_3_code :JPN,
   :name "Japan"},
  :BF
  {:currency :XOF,
   :alpha_2_code :BF,
   :alpha_3_code :BFA,
   :name "Burkina Faso"},
  :TD
  {:currency :XAF,
   :alpha_2_code :TD,
   :alpha_3_code :TCD,
   :name "Chad"},
  :SS
  {:currency :SSP,
   :alpha_2_code :SS,
   :alpha_3_code :SSD,
   :name "South Sudan"},
  :KM
  {:currency :KMF,
   :alpha_2_code :KM,
   :alpha_3_code :COM,
   :name "Comoros"},
  :GW
  {:currency :XOF,
   :alpha_2_code :GW,
   :alpha_3_code :GNB,
   :name "Guinea-Bissau"},
  :ER
  {:currency :ERN,
   :alpha_2_code :ER,
   :alpha_3_code :ERI,
   :name "Eritrea"},
  :RE
  {:currency :EUR,
   :alpha_2_code :RE,
   :alpha_3_code :REU,
   :name "Réunion"},
  :NG
  {:currency :NGN,
   :alpha_2_code :NG,
   :alpha_3_code :NGA,
   :name "Nigeria"},
  :JE
  {:currency :GBP,
   :alpha_2_code :JE,
   :alpha_3_code :JEY,
   :name "Jersey"},
  :GM
  {:currency :GMD,
   :alpha_2_code :GM,
   :alpha_3_code :GMB,
   :name "Gambia"},
  :NF
  {:currency :AUD,
   :alpha_2_code :NF,
   :alpha_3_code :NFK,
   :name "Norfolk Island"},
  :BR
  {:currency :BRL,
   :alpha_2_code :BR,
   :alpha_3_code :BRA,
   :name "Brazil"},
  :BT
  {:currency :INR,
   :alpha_2_code :BT,
   :alpha_3_code :BTN,
   :name "Bhutan"},
  :HK
  {:currency :HKD,
   :alpha_2_code :HK,
   :alpha_3_code :HKG,
   :name "Hong Kong"},
  :JM
  {:currency :JMD,
   :alpha_2_code :JM,
   :alpha_3_code :JAM,
   :name "Jamaica"},
  :UY
  {:currency :UYU,
   :alpha_2_code :UY,
   :alpha_3_code :URY,
   :name "Uruguay"},
  :GS
  {:currency nil,
   :alpha_2_code :GS,
   :alpha_3_code :SGS,
   :name "South Georgia and the South Sandwich Islands"},
  :BW
  {:currency :BWP,
   :alpha_2_code :BW,
   :alpha_3_code :BWA,
   :name "Botswana"},
  :EE
  {:currency :EUR,
   :alpha_2_code :EE,
   :alpha_3_code :EST,
   :name "Estonia"},
  :CR
  {:currency :CRC,
   :alpha_2_code :CR,
   :alpha_3_code :CRI,
   :name "Costa Rica"},
  :MN
  {:currency :MNT,
   :alpha_2_code :MN,
   :alpha_3_code :MNG,
   :name "Mongolia"},
  :TR
  {:currency :TRY,
   :alpha_2_code :TR,
   :alpha_3_code :TUR,
   :name "Turkey"},
  :FK
  {:currency :FKP,
   :alpha_2_code :FK,
   :alpha_3_code :FLK,
   :name "Falkland Islands (Malvinas)"},
  :LT
  {:currency :LTL,
   :alpha_2_code :LT,
   :alpha_3_code :LTU,
   :name "Lithuania"},
  :TM
  {:currency :TMT,
   :alpha_2_code :TM,
   :alpha_3_code :TKM,
   :name "Turkmenistan"},
  :NC
  {:currency :XPF,
   :alpha_2_code :NC,
   :alpha_3_code :NCL,
   :name "New Caledonia"},
  :IE
  {:currency :EUR,
   :alpha_2_code :IE,
   :alpha_3_code :IRL,
   :name "Ireland"},
  :ES
  {:currency :EUR,
   :alpha_2_code :ES,
   :alpha_3_code :ESP,
   :name "Spain"},
  :ZA
  {:currency :ZAR,
   :alpha_2_code :ZA,
   :alpha_3_code :ZAF,
   :name "South Africa"},
  :MZ
  {:currency :MZN,
   :alpha_2_code :MZ,
   :alpha_3_code :MOZ,
   :name "Mozambique"},
  :CG
  {:currency :XAF,
   :alpha_2_code :CG,
   :alpha_3_code :COG,
   :name "Congo"},
  :AT
  {:currency :EUR,
   :alpha_2_code :AT,
   :alpha_3_code :AUT,
   :name "Austria"},
  :AS
  {:currency :USD,
   :alpha_2_code :AS,
   :alpha_3_code :ASM,
   :name "American Samoa"},
  :PW
  {:currency :USD,
   :alpha_2_code :PW,
   :alpha_3_code :PLW,
   :name "Palau"},
  :SL
  {:currency :SLL,
   :alpha_2_code :SL,
   :alpha_3_code :SLE,
   :name "Sierra Leone"},
  :TW
  {:currency :TWD,
   :alpha_2_code :TW,
   :alpha_3_code :TWN,
   :common_name "Taiwan",
   :name "Taiwan, Province of China"},
  :BH
  {:currency :BHD,
   :alpha_2_code :BH,
   :alpha_3_code :BHR,
   :name "Bahrain"},
  :SD
  {:currency :SDG,
   :alpha_2_code :SD,
   :alpha_3_code :SDN,
   :name "Sudan"},
  :GE
  {:currency :GEL,
   :alpha_2_code :GE,
   :alpha_3_code :GEO,
   :name "Georgia"},
  :TJ
  {:currency :TJS,
   :alpha_2_code :TJ,
   :alpha_3_code :TJK,
   :name "Tajikistan"},
  :RW
  {:currency :RWF,
   :alpha_2_code :RW,
   :alpha_3_code :RWA,
   :name "Rwanda"},
  :TN
  {:currency :TND,
   :alpha_2_code :TN,
   :alpha_3_code :TUN,
   :name "Tunisia"},
  :AG
  {:currency :XCD,
   :alpha_2_code :AG,
   :alpha_3_code :ATG,
   :name "Antigua and Barbuda"},
  :BG
  {:currency :BGN,
   :alpha_2_code :BG,
   :alpha_3_code :BGR,
   :name "Bulgaria"},
  :NO
  {:currency :NOK,
   :alpha_2_code :NO,
   :alpha_3_code :NOR,
   :name "Norway"},
  :TC
  {:currency :USD,
   :alpha_2_code :TC,
   :alpha_3_code :TCA,
   :name "Turks and Caicos Islands"},
  :GH
  {:currency :GHS,
   :alpha_2_code :GH,
   :alpha_3_code :GHA,
   :name "Ghana"},
  :PK
  {:currency :PKR,
   :alpha_2_code :PK,
   :alpha_3_code :PAK,
   :name "Pakistan"},
  :GR
  {:currency :EUR,
   :alpha_2_code :GR,
   :alpha_3_code :GRC,
   :name "Greece"},
  :IM
  {:currency :GBP,
   :alpha_2_code :IM,
   :alpha_3_code :IMN,
   :name "Isle of Man"},
  :AZ
  {:currency :AZN,
   :alpha_2_code :AZ,
   :alpha_3_code :AZE,
   :name "Azerbaijan"},
  :MP
  {:currency :USD,
   :alpha_2_code :MP,
   :alpha_3_code :MNP,
   :name "Northern Mariana Islands"},
  :TK
  {:currency :NZD,
   :alpha_2_code :TK,
   :alpha_3_code :TKL,
   :name "Tokelau"},
  :YE
  {:currency :YER,
   :alpha_2_code :YE,
   :alpha_3_code :YEM,
   :name "Yemen"},
  :MR
  {:currency :MRO,
   :alpha_2_code :MR,
   :alpha_3_code :MRT,
   :name "Mauritania"},
  :AO
  {:currency :AOA,
   :alpha_2_code :AO,
   :alpha_3_code :AGO,
   :name "Angola"},
  :SY
  {:currency :SYP,
   :alpha_2_code :SY,
   :alpha_3_code :SYR,
   :name "Syrian Arab Republic"},
  :AX
  {:currency :EUR,
   :alpha_2_code :AX,
   :alpha_3_code :ALA,
   :name "Åland Islands"},
  :MY
  {:currency :MYR,
   :alpha_2_code :MY,
   :alpha_3_code :MYS,
   :name "Malaysia"},
  :FR
  {:currency :EUR,
   :alpha_2_code :FR,
   :alpha_3_code :FRA,
   :name "France"},
  :MQ
  {:currency :EUR,
   :alpha_2_code :MQ,
   :alpha_3_code :MTQ,
   :name "Martinique"},
  :TT
  {:currency :TTD,
   :alpha_2_code :TT,
   :alpha_3_code :TTO,
   :name "Trinidad and Tobago"},
  :ML
  {:currency :XOF,
   :alpha_2_code :ML,
   :alpha_3_code :MLI,
   :name "Mali"},
  :NP
  {:currency :NPR,
   :alpha_2_code :NP,
   :alpha_3_code :NPL,
   :name "Nepal"},
  :BD
  {:currency :BDT,
   :alpha_2_code :BD,
   :alpha_3_code :BGD,
   :name "Bangladesh"},
  :PL
  {:currency :PLN,
   :alpha_2_code :PL,
   :alpha_3_code :POL,
   :name "Poland"},
  :FI
  {:currency :EUR,
   :alpha_2_code :FI,
   :alpha_3_code :FIN,
   :name "Finland"},
  :MT
  {:currency :EUR,
   :alpha_2_code :MT,
   :alpha_3_code :MLT,
   :name "Malta"},
  :BY
  {:currency :BYR,
   :alpha_2_code :BY,
   :alpha_3_code :BLR,
   :name "Belarus"},
  :CH
  {:currency :CHF,
   :alpha_2_code :CH,
   :alpha_3_code :CHE,
   :name "Switzerland"},
  :VI
  {:currency :USD,
   :alpha_2_code :VI,
   :alpha_3_code :VIR,
   :name "Virgin Islands, U.S."},
  :FM
  {:currency :USD,
   :alpha_2_code :FM,
   :alpha_3_code :FSM,
   :name "Micronesia, Federated States of"},
  :EG
  {:currency :EGP,
   :alpha_2_code :EG,
   :alpha_3_code :EGY,
   :name "Egypt"},
  :ET
  {:currency :ETB,
   :alpha_2_code :ET,
   :alpha_3_code :ETH,
   :name "Ethiopia"},
  :SB
  {:currency :SBD,
   :alpha_2_code :SB,
   :alpha_3_code :SLB,
   :name "Solomon Islands"},
  :MW
  {:currency :MWK,
   :alpha_2_code :MW,
   :alpha_3_code :MWI,
   :name "Malawi"},
  :NE
  {:currency :XOF,
   :alpha_2_code :NE,
   :alpha_3_code :NER,
   :name "Niger"},
  :MM
  {:currency :MMK,
   :alpha_2_code :MM,
   :alpha_3_code :MMR,
   :name "Myanmar"},
  :DZ
  {:currency :DZD,
   :alpha_2_code :DZ,
   :alpha_3_code :DZA,
   :name "Algeria"},
  :CZ
  {:currency :CZK,
   :alpha_2_code :CZ,
   :alpha_3_code :CZE,
   :name "Czech Republic"},
  :BS
  {:currency :BSD,
   :alpha_2_code :BS,
   :alpha_3_code :BHS,
   :name "Bahamas"},
  :MH
  {:currency :USD,
   :alpha_2_code :MH,
   :alpha_3_code :MHL,
   :name "Marshall Islands"},
  :KZ
  {:currency :KZT,
   :alpha_2_code :KZ,
   :alpha_3_code :KAZ,
   :name "Kazakhstan"},
  :KR
  {:currency :KRW,
   :alpha_2_code :KR,
   :alpha_3_code :KOR,
   :name "Korea, Republic of"},
  :HU
  {:currency :HUF,
   :alpha_2_code :HU,
   :alpha_3_code :HUN,
   :name "Hungary"},
  :KG
  {:currency :KGS,
   :alpha_2_code :KG,
   :alpha_3_code :KGZ,
   :name "Kyrgyzstan"},
  :GY
  {:currency :GYD,
   :alpha_2_code :GY,
   :alpha_3_code :GUY,
   :name "Guyana"},
  :PA
  {:currency :USD,
   :alpha_2_code :PA,
   :alpha_3_code :PAN,
   :name "Panama"},
  :BV
  {:currency :NOK,
   :alpha_2_code :BV,
   :alpha_3_code :BVT,
   :name "Bouvet Island"},
  :PH
  {:currency :PHP,
   :alpha_2_code :PH,
   :alpha_3_code :PHL,
   :name "Philippines"},
  :CW
  {:currency :ANG,
   :alpha_2_code :CW,
   :alpha_3_code :CUW,
   :name "Curaçao"},
  :PG
  {:currency :PGK,
   :alpha_2_code :PG,
   :alpha_3_code :PNG,
   :name "Papua New Guinea"},
  :MS
  {:currency :XCD,
   :alpha_2_code :MS,
   :alpha_3_code :MSR,
   :name "Montserrat"},
  :NA
  {:currency :ZAR,
   :alpha_2_code :NA,
   :alpha_3_code :NAM,
   :name "Namibia"},
  :UM
  {:currency :USD,
   :alpha_2_code :UM,
   :alpha_3_code :UMI,
   :name "United States Minor Outlying Islands"},
  :SJ
  {:currency :NOK,
   :alpha_2_code :SJ,
   :alpha_3_code :SJM,
   :name "Svalbard and Jan Mayen"},
  :UA
  {:currency :UAH,
   :alpha_2_code :UA,
   :alpha_3_code :UKR,
   :name "Ukraine"},
  :AM
  {:currency :AMD,
   :alpha_2_code :AM,
   :alpha_3_code :ARM,
   :name "Armenia"},
  :DM
  {:currency :XCD,
   :alpha_2_code :DM,
   :alpha_3_code :DMA,
   :name "Dominica"},
  :GN
  {:currency :GNF,
   :alpha_2_code :GN,
   :alpha_3_code :GIN,
   :name "Guinea"},
  :NU
  {:currency :NZD,
   :alpha_2_code :NU,
   :alpha_3_code :NIU,
   :name "Niue"},
  :NZ
  {:currency :NZD,
   :alpha_2_code :NZ,
   :alpha_3_code :NZL,
   :name "New Zealand"},
  :DE
  {:currency :EUR,
   :alpha_2_code :DE,
   :alpha_3_code :DEU,
   :name "Germany"},
  :GA
  {:currency :XAF,
   :alpha_2_code :GA,
   :alpha_3_code :GAB,
   :name "Gabon"},
  :TG
  {:currency :XOF,
   :alpha_2_code :TG,
   :alpha_3_code :TGO,
   :name "Togo"},
  :LI
  {:currency :CHF,
   :alpha_2_code :LI,
   :alpha_3_code :LIE,
   :name "Liechtenstein"},
  :CD
  {:currency :CDF,
   :alpha_2_code :CD,
   :alpha_3_code :COD,
   :name "Congo, The Democratic Republic of the"}})

